In [1]:
import numpy as np

m=2; n=3
rs = np.zeros((m,n))
perm = []
count_red = 0
count_black = m * n / 2
for i in range(m):
    for j in range(n):
        if not (i+j)%2:
            rs[i][j] = count_red
            perm.append(count_red)
            count_red += 1
        else:
            rs[i][j] = count_black
            perm.append(count_black)
            count_black += 1

perm = np.array([int(i) for i in perm])
P = np.eye(6)[perm]
print(P)

A = np.array([
    [ 4,-1, 0, 1, 0, 0],
    [-1, 4,-1, 0, 1, 0],
    [ 0,-1, 4, 0, 0, 1],
    [ 1, 0, 0, 4,-1, 0],
    [ 0, 1, 0,-1, 4,-1],
    [ 0, 0, 1, 0,-1, 4]
])

A_hat = P.T @ A @ P
print(A_hat)

[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[ 4.  0.  0. -1.  1.  0.]
 [ 0.  4.  0. -1.  0.  1.]
 [ 0.  0.  4.  1. -1. -1.]
 [-1. -1.  1.  4.  0.  0.]
 [ 1.  0. -1.  0.  4.  0.]
 [ 0.  1. -1.  0.  0.  4.]]


In [6]:
rs

array([[0., 3., 1.],
       [4., 2., 5.]])

In [11]:
b = np.array([1 for i in range(6)])
b_hat = P.T @ b
b_hat

array([1., 1., 1., 1., 1., 1.])

In [ ]:
Dr = A_hat[0:3, 0:3]
Dr

array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]])

In [18]:
Ds = A_hat[3:6, 3:6]
Ds

array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]])

In [20]:
E = A_hat[3:6, 0:3]
F = A_hat[0:3, 3:6]
E

array([[-1., -1.,  1.],
       [ 1.,  0., -1.],
       [ 0.,  1., -1.]])